
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADDO AND ASSIGN BEG BOOLEAN BRACKET_CLOSE BRACKET_OPEN CALL CASE CDOWN CLEFT COLON COLOR COM CRIGHT CUP DEF DIV DIVO DOWN ELSE END EQ EQUAL FOR GEQ GREATER GT ID LEFT LEQ LOOP LT MAIN MINUS MULT MULTO NEQ NUMBER OR PAR_CLOSE PAR_OPEN PLUS POS POSX POSY PRINTLN PROC PUT P_CLOSE P_OPEN RANDOM REPEAT RIGHT SEMICOLON SMALLER SUBSTR SUMO THEN TO UNTIL UP WHEN WHEND WHILEn1 : NUMBER\n          | operation\n          | BOOLEANn2 : NUMBER\n          | operation\n          | IDn3 : NUMBER\n          | IDn4 : NUMBER\n          | operation\n          | ID\n          | BOOLEANn5 : NUMBER\n          | ID\n          | BOOLEANn6 : NUMBER\n          | BOOLEANoperation : add\n                  add : ADDO PAR_OPEN ID PAR_CLOSE SEMICOLON\n           | ADDO PAR_OPEN ID COLON n2 PAR_CLOSE SEMICOLON'
    
_lr_action_items = {'NUMBER':([0,10,],[2,14,]),'BOOLEAN':([0,],[4,]),'ADDO':([0,10,],[6,6,]),'$end':([1,2,3,4,5,11,17,],[0,-1,-2,-3,-18,-19,-20,]),'PAR_CLOSE':([5,8,11,12,13,14,15,17,],[-18,9,-19,-6,16,-4,-5,-20,]),'PAR_OPEN':([6,],[7,]),'ID':([7,10,],[8,12,]),'COLON':([8,],[10,]),'SEMICOLON':([9,16,],[11,17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'n1':([0,],[1,]),'operation':([0,10,],[3,15,]),'add':([0,10,],[5,5,]),'n2':([10,],[13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> n1","S'",1,None,None,None),
  ('n1 -> NUMBER','n1',1,'p_n1','parser.py',7),
  ('n1 -> operation','n1',1,'p_n1','parser.py',8),
  ('n1 -> BOOLEAN','n1',1,'p_n1','parser.py',9),
  ('n2 -> NUMBER','n2',1,'p_n2','parser.py',25),
  ('n2 -> operation','n2',1,'p_n2','parser.py',26),
  ('n2 -> ID','n2',1,'p_n2','parser.py',27),
  ('n3 -> NUMBER','n3',1,'p_n3','parser.py',43),
  ('n3 -> ID','n3',1,'p_n3','parser.py',44),
  ('n4 -> NUMBER','n4',1,'p_n4','parser.py',57),
  ('n4 -> operation','n4',1,'p_n4','parser.py',58),
  ('n4 -> ID','n4',1,'p_n4','parser.py',59),
  ('n4 -> BOOLEAN','n4',1,'p_n4','parser.py',60),
  ('n5 -> NUMBER','n5',1,'p_n5','parser.py',81),
  ('n5 -> ID','n5',1,'p_n5','parser.py',82),
  ('n5 -> BOOLEAN','n5',1,'p_n5','parser.py',83),
  ('n6 -> NUMBER','n6',1,'p_n6','parser.py',102),
  ('n6 -> BOOLEAN','n6',1,'p_n6','parser.py',103),
  ('operation -> add','operation',1,'p_operation','parser.py',118),
  ('add -> ADDO PAR_OPEN ID PAR_CLOSE SEMICOLON','add',5,'p_add','parser.py',123),
  ('add -> ADDO PAR_OPEN ID COLON n2 PAR_CLOSE SEMICOLON','add',7,'p_add','parser.py',124),
]
